import 'dotenv/config'
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3'
import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { PrismaClient } from '../server/generated/prisma/client.ts'

const adapter = new PrismaBetterSqlite3({
  url: process.env.DATABASE_URL || 'file:./data/site.sqlite',
})
const prisma = new PrismaClient({ adapter })
const outputPath = resolve(process.cwd(), 'prisma', 'seed-data.mjs')

function withoutAuditFields(row) {
  return Object.fromEntries(
    Object.entries(row).filter(([key]) => key !== 'createdAt' && key !== 'updatedAt'),
  )
}

async function main() {
  const seedData = {
    media: (await prisma.media.findMany({ orderBy: { path: 'asc' } })).map(withoutAuditFields),
    blogPosts: (await prisma.blogPost.findMany({ orderBy: { id: 'asc' } })).map((row) => ({
      ...withoutAuditFields(row),
      publishedAt: row.publishedAt?.toISOString() ?? null,
    })),
    blogSections: await prisma.blogSection.findMany({ orderBy: [{ postId: 'asc' }, { sortOrder: 'asc' }, { id: 'asc' }] }),
    contactSettings: (await prisma.contactSettings.findMany({ orderBy: { id: 'asc' } })).map(withoutAuditFields),
    siteSettings: (await prisma.siteSettings.findMany({ orderBy: { id: 'asc' } })).map(withoutAuditFields),
    socialLinks: (await prisma.socialLink.findMany({ orderBy: [{ sortOrder: 'asc' }, { id: 'asc' }] })).map(withoutAuditFields),
    faqSections: (await prisma.faqSection.findMany({ orderBy: [{ sortOrder: 'asc' }, { id: 'asc' }] })).map(withoutAuditFields),
    faqItems: (await prisma.faqItem.findMany({ orderBy: [{ sectionId: 'asc' }, { sortOrder: 'asc' }, { id: 'asc' }] })).map(withoutAuditFields),
    aboutPages: (await prisma.aboutPage.findMany({ orderBy: { id: 'asc' } })).map(withoutAuditFields),
    aboutSections: await prisma.aboutSection.findMany({ orderBy: [{ pageId: 'asc' }, { sortOrder: 'asc' }, { id: 'asc' }] }),
    homePages: (await prisma.homePage.findMany({ orderBy: { id: 'asc' } })).map(withoutAuditFields),
    navigationItems: (await prisma.navigationItem.findMany({ orderBy: { path: 'asc' } })).map(withoutAuditFields),
    reviews: (await prisma.review.findMany({ orderBy: [{ sortOrder: 'asc' }, { id: 'asc' }] })).map(withoutAuditFields),
    featuredServices: (await prisma.featuredService.findMany({ orderBy: [{ sortOrder: 'asc' }, { id: 'asc' }] })).map(withoutAuditFields),
    serviceWaveformBars: await prisma.serviceWaveformBar.findMany({ orderBy: [{ serviceId: 'asc' }, { sortOrder: 'asc' }, { id: 'asc' }] }),
    serviceFeatures: await prisma.serviceFeature.findMany({ orderBy: [{ serviceId: 'asc' }, { sortOrder: 'asc' }, { id: 'asc' }] }),
    priceListPages: (await prisma.priceListPage.findMany({ orderBy: { id: 'asc' } })).map(withoutAuditFields),
    priceListSections: await prisma.priceListSection.findMany({ orderBy: [{ pageId: 'asc' }, { sortOrder: 'asc' }, { id: 'asc' }] }),
    priceListItems: await prisma.priceListItem.findMany({ orderBy: [{ sectionId: 'asc' }, { sortOrder: 'asc' }, { id: 'asc' }] }),
    priceListVariations: await prisma.priceListVariation.findMany({ orderBy: [{ itemId: 'asc' }, { sortOrder: 'asc' }, { id: 'asc' }] }),
  }

  const serialized = JSON.stringify(seedData, null, 2)
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
  const source = `// Generated by \`npm run db:export-seed\`. Do not edit manually.\nexport const seedData = ${serialized}\n`
  await writeFile(outputPath, source, 'utf8')

  const rowCount = Object.values(seedData).reduce((total, rows) => total + rows.length, 0)
  console.log(`Exported ${rowCount} content rows to ${outputPath}`)
  console.log('Upload files are not copied; keep the referenced files in data/uploads.')
}

main()
  .catch((error) => {
    console.error(error)
    process.exitCode = 1
  })
  .finally(() => prisma.$disconnect())
